apiVersion: v1
kind: Service
metadata:
  name: vprodb #same name as in our application.properties file in our application
spec:
  ports:
    - port: 3306 #will accept the request at 3306 and send it to the back end
      targetPort: vprodb-port #we can give port or port name
      protocol: TCP
  selector:
    app: vprodb #backend port (label of our pod)
  type: ClusterIP