apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  ports:
    - port: 80
      targetPort: vproapp-port # this is port 8080
      protocol: TCP
  selector:
    app: vproapp
  type: LoadBalancer # it will lunch an elastic load balancer